const Joi = require('joi');

const affiliateMarketingAddValidation = Joi.object({
  first_name: Joi.string(),
  middle_name: Joi.string(),
  uniqueID: Joi.string(),
  last_name: Joi.string(),
  email: Joi.string(),
  dob: Joi.string(),
  mobile_number: Joi.string(),
  pan_number: Joi.string(),
  aadhar_number: Joi.string(),
  dl_number: Joi.string(),
  pin_code: Joi.string(),
  city_name: Joi.string(),
  state_name: Joi.string(),
  loan_amount: Joi.string(),
  loan_duration: Joi.string(),
  resident_ownership: Joi.string(),
  customer_profile: Joi.string(),
  business_name: Joi.string(),
  business_pincode: Joi.string(),
  last_twelve_month_sales: Joi.string(),
  constitution: Joi.string(),
  number_of_years_in_business: Joi.string(),
  business_annual_turnover: Joi.string(),
  loan_type: Joi.string(),
  utm_source: Joi.string(),
  utm_campaign: Joi.string(),
  utm_medium: Joi.string(),
  income: Joi.string(),
  ownership_proof: Joi.string(),
  is_gst_registered: Joi.string(),
});

const affiliateMarketingUpdateValidation = Joi.object({
  first_name: Joi.string(),
  uniqueID: Joi.string(),
  middle_name: Joi.string(),
  last_name: Joi.string(),
  email: Joi.string(),
  dob: Joi.string(),
  mobile_number: Joi.string(),
  pan_number: Joi.string(),
  aadhar_number: Joi.string(),
  dl_number: Joi.string(),
  pin_code: Joi.string(),
  city_name: Joi.string(),
  state_name: Joi.string(),
  loan_amount: Joi.string(),
  loan_duration: Joi.string(),
  resident_ownership: Joi.string(),
  customer_profile: Joi.string(),
  business_name: Joi.string(),
  business_pincode: Joi.string(),
  last_twelve_month_sales: Joi.string(),
  constitution: Joi.string(),
  number_of_years_in_business: Joi.string(),
  business_annual_turnover: Joi.string(),
  loan_type: Joi.string(),
  utm_source: Joi.string(),
  utm_campaign: Joi.string(),
  utm_medium: Joi.string(),
  income: Joi.string(),
  ownership_proof: Joi.string(),
  is_gst_registered: Joi.string(),
});

module.exports = {
  affiliateMarketingAddValidation,
  affiliateMarketingUpdateValidation,
};
